### ISSUE TITLE
Can't change background color

### ISSUE THREAD

**Issue by beetwnus** [Elisniper/Glass-Wave#1]
[
![螢幕擷取畫面 2023-04-25 134240](https://user-images.githubusercontent.com/131743022/234185227-6414b18d-f454-4c89-90cc-a0605817de0b.png)
](url)
![螢幕擷取畫面 2023-04-25 134905](https://user-images.githubusercontent.com/131743022/234185606-c992c08e-5b09-4412-b068-f4500f27f8b5.png)

I use code like this, but the color of background doesn't change

**Comment by Elisniper** [comment]
Made a typo on the variables for read me/instuctions my bad

They need to be: 

--var-chat-bubbles-background
--var-chat-bubbles-edge-background

**Comment by beetwnus** [comment]
> Made a typo on the variables for read me/instuctions my bad
> 
> They need to be:
> 
> --var-chat-bubbles-background --var-chat-bubbles-edge-background

Thanks for your help !

![Image 2](https://user-images.githubusercontent.com/131743022/234227115-45f55d6c-037c-4558-966a-5cf8682ae881.png)  ![Image 2](https://user-images.githubusercontent.com/131743022/234226795-3bff4502-0609-4be9-86f7-3e4ef8c6458c.png)
And can I change the color of other part(eg. background color of icons and the selected channel) ?

**Comment by Elisniper** [comment]
Yea you can add the bellow as well in that code

--var-accent: custom color ;
