### ISSUE TITLE
mute and deafen button icons broken with gameactivitytoggle installed

### ISSUE THREAD

**Issue by RandomHuman2020** [Elisniper/Glass-Wave#4]
when [GameActivityToggle](https://betterdiscord.app/plugin/GameActivityToggle) is installed with this theme, the Mute and Deafen button icons break, showing the deafen button for mute and the settings icon for deafen. This problem does not appear with other themes i've tried, only with this one.
![image](https://github.com/Elisniper/Glass-Wave/assets/73597826/834af71f-fd40-4364-941e-08cda6eabf69)

**Comment by Elisniper** [comment]
This should now be fixed with the latest update
